spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/catalogue
    username: postgres
    password: postgres
  flyway:
    schemas:
      - public
      - catalogue
  jpa:
    show-sql: true
server:
  port: 8081
logging:
  level:
    sql: info